import "./globals.css";
import type { Metadata } from "next";
import { Providergoogle } from "./Providergoogle";
import Navbar from "./Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Providergoogle>
           <Navbar/>
           {children}
           </Providergoogle>
      </body>
    </html>
  );
}
